config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy

    redirect_to flats_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guest, :picture_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
  <%= f.error_notification %>

  <%= f.input :name %>

  <%= f.input :address %>

  <%= f.input :description %>

  <%= f.input :price_per_night %>

  <%= f.input :number_of_guest %>

  <%= f.input :picture_url %>

  <%= f.button :submit, class: "btn-primary" %>
  <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/flats/edit.html.erb
<div class="container mt-5">
  <h1>Modifier l'appartement <%= @flat.name %></h1>

  <%= render 'form', flat: @flat %>
</div>

app/views/flats/index.html.erb
<div class="container mt-5 mb-5">
  <h1 class="mb-3">Tous nos appartements</h1>
  <div class="row g-3">
    <% @flats.each do |flat| %>
      <div class="card col-sm-4">
        <img src="<%= flat.picture_url %>" class="card-img-top" alt="flat">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.description.first(150) %></p>
        </div>
        <div class="card-footer">
          <p><i class="fa-solid fa-dollar-sign"></i> <%= flat.price_per_night %> per night<br><i class="fa-sharp fa-solid fa-person"></i> <%= flat.number_of_guest %> persons</p>
          <%= link_to "Plus de détails", flat_path(flat), class: 'btn btn-primary' %>
          <%= link_to '<i class="fa-solid fa-pen-to-square"></i>'.html_safe , edit_flat_path(flat) %>
          <%= link_to '<i class="fa-solid fa-trash"></i>'.html_safe, flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container mt-5">
  <h1>Ajouter un appartement</h1>

  <%= render 'form', flat: @flat %>
</div>

app/views/flats/show.html.erb
<div class="img">
  <img src="<%= @flat.picture_url %>" alt="flat_banner">
</div>
<div class="container mt-5 on-top">
  <div class="card mt-5">
    <div class="card-body">
      <h1><%= @flat.name %></h1>
      <p><%= @flat.address %></p>
    </div>
  </div>
  <div class="card mt-3">
    <div class="card-body">
      <h4>Détails</h4>
      <p>Prix : <%= @flat.price_per_night %>$
      <br>Capacité : <%= @flat.number_of_guest %> personnes</p>
    </div>
  </div>
  <div class="card mt-3">
    <div class="card-body">
      <h4>Description</h4>
      <p><%= @flat.description %></p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/flats">Simple Airbnb</a>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link" href="/flats">Home</a>
          <a class="nav-link" href="/flats/new">Ajouter un appartement</a>
        </div>
      </div>
    </div>
  </nav>
  <%= yield %>
  </body>
</html>